// Headless demo: compile a hand-built plan into a standalone `runGraph` module and
// print it. Proves the plugin runs under bare Node with NO React present — it
// reaches the host library only through the React-free `/contract` subpath.
//
// Run (after `npm run build`): `npm run demo`.
import { emitGraph } from '@theclearsky/react-blender-nodes-codegen';
import { plan, state } from './fixture.mjs';

const source = await emitGraph(plan, state, { exportRunGraph: true });

process.stdout.write(
  '// ── Generated by @theclearsky/react-blender-nodes-codegen (emitGraph) ──\n',
);
process.stdout.write(source);
process.stdout.write('\n');
